/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author PC
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barMenu = new javax.swing.JMenuBar();
        menuEjemploFecha = new javax.swing.JMenu();
        itemManejoFechas = new javax.swing.JMenuItem();
        itemJFormatted = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuEjemploFecha.setText("EjemploFecha");

        itemManejoFechas.setText("Manejo Fechas");
        itemManejoFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManejoFechasActionPerformed(evt);
            }
        });
        menuEjemploFecha.add(itemManejoFechas);

        itemJFormatted.setText("JFormattedTextField");
        itemJFormatted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemJFormattedActionPerformed(evt);
            }
        });
        menuEjemploFecha.add(itemJFormatted);

        barMenu.add(menuEjemploFecha);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemManejoFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManejoFechasActionPerformed
        VentanaManejoFechas vent= new VentanaManejoFechas();
        vent.setVisible(true);
    }//GEN-LAST:event_itemManejoFechasActionPerformed

    private void itemJFormattedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemJFormattedActionPerformed
        VentanaJFormatter vent= new VentanaJFormatter();
        vent.setVisible(true);
    }//GEN-LAST:event_itemJFormattedActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JMenuItem itemJFormatted;
    private javax.swing.JMenuItem itemManejoFechas;
    private javax.swing.JMenu menuEjemploFecha;
    // End of variables declaration//GEN-END:variables
}
